package org.lasarimanstudios.escapedungeon.assets;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.assets.AssetManager;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.TextureRegion;

import java.util.*;

/**
 * Small wrapper around LibGDX's {@link com.badlogic.gdx.assets.AssetManager}.
 *
 * <p>This centralizes texture loading so gameplay code can request textures by internal asset path.
 * All {@code .png} files under {@code textures/} are auto-discovered from {@code assets.txt}
 * (generated by the Gradle build) and bulk-loaded at startup — no manual registration required.
 * Simply drop a new {@code .png} into the {@code assets/textures/} folder and rebuild.</p>
 *
 * <p>Textures returned by this class are owned by the underlying {@link AssetManager} and must not be
 * disposed by callers. Call {@link #dispose()} when the owning screen/game no longer needs the assets.</p>
 */
public class GameAssets {

	// ── Well-known path aliases (used by gameplay code for compile-time safety) ──

	// World / entities
	public static final String TEX_BLOOD_PUDDLE = "textures/objects/blood-puddle.png";
	public static final String TEX_CHEST_CLOSED = "textures/objects/chest/chest_closed.png";
	public static final String TEX_CHEST_OPEN = "textures/objects/chest/chest_open.png";
	public static final String TEX_WALL_ORIGINAL = "textures/objects/walls/wall.png";

	// Player + weapon
	public static final String TEX_WEAPON_SWORD_BASIC = "textures/weapons/sword_basic.png";
	public static final String TEX_WEAPON_SWORD_BLUE = "textures/weapons/sword_blue.png";
	public static final String TEX_WEAPON_SWORD_FAT = "textures/weapons/sword_fat.png";
	public static final String TEX_WEAPON_SWORD_GOLD = "textures/weapons/sword_gold.png";
	public static final String TEX_WEAPON_SWORD_IRON = "textures/weapons/sword_iron.png";
	public static final String TEX_WEAPON_SWORD_PINK = "textures/weapons/sword_pink.png";
	public static final String TEX_WEAPON_SWORD_RAINBOW = "textures/weapons/sword_rainbow.png";
	public static final String TEX_WEAPON_SWORD_YELLOW = "textures/weapons/sword_yellow.png";
	public static final String TEX_WEAPON_RGB_SABER = "textures/weapons/rgb_saber.png";
	public static final String TEX_PLAYER_LEFT_IDLE = "textures/characters/character-01/character-01-links-stehend.png";

	private final AssetManager assetManager = new AssetManager();
	/**
	 * Cached per-enemy sprite sets, keyed by enemy folder id (e.g. "goblin-01", "ghost").
	 */
	private final Map<String, EnemySpriteSet> enemySpriteSets = new HashMap<>();
	/**
	 * Paths that were auto-discovered and loaded.
	 */
	private List<String> loadedTexturePaths = Collections.emptyList();

	private static String normalizeWallTextureRef(String ref) {
		if (ref == null || ref.isBlank()) {
			return TEX_WALL_ORIGINAL;
		}
		String trimmed = ref.trim();
		// Already a full internal assets path.
		if (trimmed.startsWith("textures/")) {
			return trimmed;
		}

		String filename = trimmed;
		// Legacy: "Wall-A1.png" -> "wall_A1.png"
		if (filename.startsWith("Wall-")) {
			filename = "wall_" + filename.substring("Wall-".length());
		}
		// Legacy: "Map-01.png" etc. isn't a wall; but for walls we just normalize case a bit.
		if (filename.equalsIgnoreCase("wall.png")) {
			filename = "wall.png";
		}
		if (filename.toLowerCase().startsWith("wall-") && filename.toLowerCase().endsWith(".png")) {
			// Another possible legacy: "wall-A1.png" -> "wall_A1.png"
			filename = "wall_" + filename.substring("wall-".length());
		}
		return "textures/objects/walls/" + filename;
	}

	/**
	 * Scans {@code assets.txt} and returns all {@code .png} paths under {@code textures/}.
	 *
	 * <p>{@code assets.txt} is auto-generated by the Gradle build and lists every file in the
	 * assets directory. This makes auto-discovery reliable across all LibGDX backends (desktop,
	 * Android, web) where {@code FileHandle.list()} may not work.</p>
	 */
	private static List<String> discoverTextures() {
		List<String> paths = new ArrayList<>();
		String listing = Gdx.files.internal("assets.txt").readString("UTF-8");
		for (String line : listing.split("\\r?\\n")) {
			String trimmed = line.trim();
			if (trimmed.startsWith("textures/") && trimmed.endsWith(".png")) {
				paths.add(trimmed);
			}
		}
		return paths;
	}

	/**
	 * Auto-discovers and loads all {@code .png} textures under {@code textures/} from
	 * {@code assets.txt}, then blocks until finished.
	 *
	 * <p>To add a new texture, simply place the {@code .png} file in the {@code assets/textures/}
	 * folder and rebuild — no code changes needed.</p>
	 */
	public void load() {
		List<String> paths = discoverTextures();
		for (String path : paths) {
			assetManager.load(path, Texture.class);
		}
		assetManager.finishLoading();
		loadedTexturePaths = Collections.unmodifiableList(paths);
		Gdx.app.log("GameAssets", "Auto-loaded " + paths.size() + " textures from assets.txt");
	}

	/**
	 * Returns the list of texture paths that were auto-discovered and loaded. Useful for debugging.
	 */
	public List<String> getLoadedPaths() {
		return loadedTexturePaths;
	}

	/**
	 * Returns a previously loaded texture.
	 *
	 * @param internalPath internal asset path (e.g. {@code textures/...png})
	 * @return loaded texture
	 * @throws com.badlogic.gdx.utils.GdxRuntimeException if the asset isn't loaded
	 */
	public Texture getTexture(String internalPath) {
		return assetManager.get(internalPath, Texture.class);
	}

	/**
	 * Convenience method that ensures a texture is loaded and then returns it.
	 *
	 * <p>This is useful during development as a safe fallback for assets that weren't preloaded.</p>
	 *
	 * @param internalPath internal asset path
	 * @return loaded texture
	 */
	public Texture createTexture(String internalPath) {
		// Minimal, safe transition helper: if a texture isn't preloaded, load it now.
		if (!assetManager.isLoaded(internalPath, Texture.class)) {
			assetManager.load(internalPath, Texture.class);
			assetManager.finishLoading();
		}
		return getTexture(internalPath);
	}

	public TextureRegion getRegion(String internalPath) {
		return new TextureRegion(getTexture(internalPath));
	}

	/**
	 * Returns (and caches) a sprite set for the given enemy id.
	 *
	 * <p>The {@code enemyId} corresponds to the folder name under {@code textures/enemy/},
	 * e.g. {@code "goblin-01"} or {@code "ghost"}. Textures are auto-discovered by naming
	 * convention — see {@link EnemySpriteSet} for details.</p>
	 *
	 * @param enemyId folder name under {@code textures/enemy/}
	 * @return the sprite set for that enemy type (never {@code null})
	 * @throws IllegalArgumentException if no matching textures were found
	 */
	public EnemySpriteSet getEnemySpriteSet(String enemyId) {
		return enemySpriteSets.computeIfAbsent(enemyId,
			id -> EnemySpriteSet.build(this, id, loadedTexturePaths));
	}

	public TextureRegion getPlayerIdle(Direction direction) {
		// Until there are directional player assets, just reuse the left-standing image.
		return getRegion(TEX_PLAYER_LEFT_IDLE);
	}

	/**
	 * Resolves a wall texture reference coming from level JSON.
	 *
	 * <p>Accepts either:</p>
	 * <ul>
	 *   <li>full internal path (e.g. {@code textures/objects/walls/wall_A1.png})</li>
	 *   <li>filename only (e.g. {@code wall_A1.png} or {@code wall.png})</li>
	 *   <li>legacy filenames (e.g. {@code Wall-A1.png})</li>
	 * </ul>
	 */
	public Texture getWallTexture(String jsonTextureRef) {
		String internalPath = normalizeWallTextureRef(jsonTextureRef);
		if (assetManager.isLoaded(internalPath, Texture.class)) {
			return getTexture(internalPath);
		}
		// In case walls are referenced that aren't part of the preload list yet,
		// keep behavior compatible and load them on demand.
		return createTexture(internalPath);
	}

	/**
	 * Disposes the underlying {@link AssetManager} and all assets loaded through it.
	 */
	public void dispose() {
		assetManager.dispose();
	}
}
